### ISSUE TITLE
Money format from locale file

### ISSUE THREAD

**Issue by rafaeldev** [wbotelhos/normalizy#2]
The example showed on documentation is little bit different from [Money gem](https://github.com/RubyMoney/money#localization):
```yaml
# config/locale/en.yml
en:
  number:
    currency:
      format:
        delimiter: ","
        separator: "."
  # falling back to
  number:
    format:
      delimiter: ","
      separator: "."
```
On money gem the currency config are scoped on `number` attribute.
The *normalizy gem* can use money configure? It's make sense?

Thanks!
